Retry fetches when syncing.
The initial `repo sync` operation sometimes fails due to transient
errors. The logs contain the following:

error: Unable to fully sync the tree
error: Checking out local projects failed.

Immediately retrying nearly always addresses the problem.

Also change the parallelism to a more reasonable number.

Test: ran it
Change-Id: Iedbb4900c46bfe098caf07ae8f012ca6c490ff6c