Retry repo sync.
It frequently fails when there are updates to large git repos, such as
kernel images. An immediate retry nearly always succeeds.

Example error:

error: Unable to fully sync the tree
error: Checking out local projects failed.
Failing repos (checkout):
device/google/laguna-kernels/6.12
device/google/pantah-kernels/6.1
device/google/pantah-kernels/6.12
device/google/raviole-kernels/6.1
device/google/shusky-kernels/6.12
etc.

Test: ran it
Change-Id: I49775aa8fea9dbb83cc5f6a2969f0718dcbfd082